[package]
name = "particle-life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "0.2.12", features = ["js"] }
macroquad = "0.4.4"
rand = "0.8.5"
rayon = "1.8.0"
